---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr1

  roles:
    - role: gantsign.sdkman
      sdkman_users: test_usr1

    - role: ansible_role_sdkman_init
      users:
        - username: test_usr1
          sdkman_install:
            - candidate: ant
              version: '1.10.1'
            - candidate: ant
              version: '1.10.0'
            - candidate: ant
              version: '1.9.9'
            - candidate: ant
              version: 'tmp'
              path: '/tmp'
          sdkman_default:
            ant: '1.10.0'
